// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;

namespace Chat_Support.Domain.Entities;

[Index("Id", Name = "IX_GroupFacilities")]
[Index("GroupId", Name = "IX_GroupFacilities_1")]
[Index("TableName", Name = "IX_GroupFacilities_2")]
[Index("FacilityId", Name = "IX_GroupFacilities_3")]
public partial class GroupFacility
{
    /// <summary>
    /// کلید
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// کد گروه کاربری - کلید به kci_groups
    /// </summary>
    public int? GroupId { get; set; }

    /// <summary>
    /// نام جدول
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string TableName { get; set; }

    /// <summary>
    /// کد امکان
    /// </summary>
    public int? FacilityId { get; set; }

    /// <summary>
    /// نوع دسترسی y/n
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string AccessType { get; set; }

    /// <summary>
    /// کد لینک - کلید به جدول CMS_Links
    /// </summary>
    public int? LinkId { get; set; }

    /// <summary>
    /// کد لینک مربوطه - کلید به جدول CMSDirectLinks
    /// </summary>
    [Column("DLinkId")]
    public int? DlinkId { get; set; }

    public virtual KciGroup Group { get; set; }
}
