// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Chat_Support.Domain.Entities;

[Table("KCI_AssignedUsers")]
[Index("GroupId", Name = "IX-GroupID")]
public partial class KciAssignedUser
{
    /// <summary>
    /// کلید
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// کد کاربر - کلید به جدول kci_users
    /// </summary>
    [StringLength(50)]
    public string UserId { get; set; }

    /// <summary>
    /// گروه کاربری - کلید به جدول kci_groups
    /// </summary>
    [StringLength(50)]
    public string GroupId { get; set; }

    public virtual KciUser User { get; set; }
    public virtual KciGroup Group { get; set; }
}
