// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Chat_Support.Domain.Entities;

[Table("KCI_Groups")]
[Index("ParentId", Name = "IX-ParentID-Includes")]
public partial class KciGroup
{
    /// <summary>
    /// کلید
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// نام گروه کاربری
    /// </summary>
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// شرح
    /// </summary>
    [StringLength(255)]
    public string Description { get; set; }

    public int? ParentId { get; set; }


    public virtual ICollection<KciAssignedUser> KciAssignedUsers { get; set; }
    public virtual ICollection<GroupFacility> GroupFacilities { get; set; }
}
