// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Chat_Support.Domain.Entities;

public partial class Region
{
    /// <summary>
    /// کلید
    /// </summary>
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// نام ناحیه/حوزه
    /// </summary>
    [Column("name")]
    [StringLength(200)]
    public string Name { get; set; }

    /// <summary>
    /// عنوان
    /// </summary>
    [Column("title")]
    [StringLength(200)]
    public string Title { get; set; }

    /// <summary>
    /// کد ناحیه بالاتر - کلید به جدول Regions
    /// </summary>
    public int? ParentId { get; set; }

    [Column("RelatedURI")]
    [StringLength(200)]
    public string RelatedUri { get; set; }

    [StringLength(1000)]
    public string KeywordsMetaTag { get; set; }

    [StringLength(1000)]
    public string DescriptionMetaTag { get; set; }

    public int? StoregeLimit { get; set; }

    public int? UsersLimit { get; set; }

    public int? DatabaseLimit { get; set; }


    public virtual ICollection<KciUser> Users { get; set; }
    public virtual ICollection<CmsUserRegion> UserRegions { get; set; }
    public virtual ICollection<ChatRoom> ChatRooms { get; set; }
}
