// <auto-generated />
using System;
using Chat_Support.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat_Support.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251013062815_AddAgentStatusManagementFields")]
    partial class AddAgentStatusManagementFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chat_Support.Domain.Entities.AbrikChatUsersToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("AbrikChatUsersTokens", (string)null);
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatFileMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("KciUserId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("UploadedDate");

                    b.ToTable("ChatFileMetadatas");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatLoginOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatLoginOtps");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("Created");

                    b.HasIndex("KciUserId");

                    b.HasIndex("ReplyToMessageId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChatRoomType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById1")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GuestIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuestUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedById1");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.HasIndex("RegionId1");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatRoomMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("KciUserId");

                    b.HasIndex("UserId", "ChatRoomId")
                        .IsUnique();

                    b.ToTable("ChatRoomMembers");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatUserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChatUserRefreshTokens");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.CmsUserRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RegionId")
                        .HasColumnType("int")
                        .HasComment("شناسه ناحیه ی اختصای به کاربر");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasComment("شناسه کاربر");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("CMS_UserRegions");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.GroupFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength()
                        .HasComment("نوع دسترسی y/n");

                    b.Property<int?>("DlinkId")
                        .HasColumnType("int")
                        .HasColumnName("DLinkId")
                        .HasComment("کد لینک مربوطه - کلید به جدول CMSDirectLinks");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasComment("کد امکان");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasComment("کد گروه کاربری - کلید به kci_groups");

                    b.Property<int?>("LinkId")
                        .HasColumnType("int")
                        .HasComment("کد لینک - کلید به جدول CMS_Links");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("نام جدول");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_GroupFacilities");

                    b.HasIndex(new[] { "GroupId" }, "IX_GroupFacilities_1");

                    b.HasIndex(new[] { "TableName" }, "IX_GroupFacilities_2");

                    b.HasIndex(new[] { "FacilityId" }, "IX_GroupFacilities_3");

                    b.ToTable("GroupFacilities");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.GuestUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("GuestUsers");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciAssignedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("گروه کاربری - کلید به جدول kci_groups");

                    b.Property<int?>("GroupId1")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کد کاربر - کلید به جدول kci_users");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId1");

                    b.HasIndex("UserId1");

                    b.HasIndex(new[] { "GroupId" }, "IX-GroupID");

                    b.ToTable("KCI_AssignedUsers");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("شرح");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام گروه کاربری");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ParentId" }, "IX-ParentID-Includes");

                    b.ToTable("KCI_Groups");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccessFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ActiveDirectoryUserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodeMeli")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CodePosti")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long?>("DateEnter")
                        .HasColumnType("bigint");

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Enable")
                        .HasColumnType("bit");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Post")
                        .HasColumnType("int");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityAnswer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityQuestion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool?>("ShowPublic")
                        .HasColumnType("bit");

                    b.Property<int?>("StafId")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WorkPlace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex(new[] { "UserName" }, "IX_KCI_UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("KCI_Users", null, t =>
                        {
                            t.HasTrigger("General_Delete_Tracking");

                            t.HasTrigger("General_Insert_Tracking");

                            t.HasTrigger("Password_Update_Tracking");

                            t.HasTrigger("trg_UpdateLastPasswordChangeDate");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.MessageReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KciUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.MessageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KciUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("MessageStatuses");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DatabaseLimit")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionMetaTag")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KeywordsMetaTag")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .HasComment("نام ناحیه/حوزه");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasComment("کد ناحیه بالاتر - کلید به جدول Regions");

                    b.Property<string>("RelatedUri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("RelatedURI");

                    b.Property<int?>("StoregeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title")
                        .HasComment("عنوان");

                    b.Property<int?>("UsersLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("AutoDetectedStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentActiveChats")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ManualStatusExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManualStatusSetAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxConcurrentChats")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Support_Agents", (string)null);
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportGuestChatRoomMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastReadMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("GuestUserId", "ChatRoomId")
                        .IsUnique();

                    b.ToTable("SupportGuestChatRoomMembers");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAgentUserId")
                        .HasColumnType("int");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("RequesterGuestId")
                        .HasColumnType("int");

                    b.Property<int?>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentUserId");

                    b.HasIndex("ChatRoomId")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.HasIndex("RequesterGuestId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("Status");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TicketReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TicketRe__3214EC077F0EA2C0");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketReplies", (string)null);
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Reminder")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("KciUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("KciUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("کلید");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength()
                        .HasComment("نوع دسترسی y/n");

                    b.Property<int?>("DlinkId")
                        .HasColumnType("int")
                        .HasColumnName("DLinkId")
                        .HasComment("کد لینک مربوطه - کلید به جدول CMSDirectLinks");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int")
                        .HasComment("ماژول مربوطه - کلید به جدول facilities");

                    b.Property<int?>("LinkId")
                        .HasColumnType("int")
                        .HasComment("کد لینک مربوطه - کلید به جدول CMS_Links");

                    b.Property<int?>("Regionid")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasComment("نام جدول مربوطه - کلید به databases");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasComment("کد کاربر مربوطه - کلید به kci_users");

                    b.HasKey("Id");

                    b.HasIndex("Regionid");

                    b.HasIndex(new[] { "Id" }, "IX_UserFacilities");

                    b.HasIndex(new[] { "UserId" }, "IX_UserFacilities_1");

                    b.HasIndex(new[] { "TableName" }, "IX_UserFacilities_2");

                    b.HasIndex(new[] { "FacilityId" }, "IX_UserFacilities_3");

                    b.ToTable("UserFacilities");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserFcmTokenInfoMobileAbrikChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("AddedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("UserFcmTokenInfoMobileAbrikChat", (string)null);
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.AbrikChatUsersToken", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatFileMetadata", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("UploadedFiles")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChatRoom");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatLoginOtp", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("SentMessages")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChatRoom");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatRoom", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("CreatedChatRooms")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById1");

                    b.HasOne("Chat_Support.Domain.Entities.GuestUser", null)
                        .WithMany("ChatRooms")
                        .HasForeignKey("GuestUserId");

                    b.HasOne("Chat_Support.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chat_Support.Domain.Entities.Region", null)
                        .WithMany("ChatRooms")
                        .HasForeignKey("RegionId1");

                    b.Navigation("CreatedBy");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatRoomMember", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Members")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("ChatRoomMemberships")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatUserRefreshToken", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.CmsUserRegion", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.Region", "Region")
                        .WithMany("UserRegions")
                        .HasForeignKey("RegionId");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany("UserRegions")
                        .HasForeignKey("UserId");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.GroupFacility", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciGroup", "Group")
                        .WithMany("GroupFacilities")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciAssignedUser", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciGroup", "Group")
                        .WithMany("KciAssignedUsers")
                        .HasForeignKey("GroupId1");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany("KciAssignedUsers")
                        .HasForeignKey("UserId1");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciUser", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.Region", "Region")
                        .WithMany("Users")
                        .HasForeignKey("RegionId");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.MessageReaction", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("MessageReactions")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.ChatMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.MessageStatus", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("MessageStatuses")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.ChatMessage", "Message")
                        .WithMany("Statuses")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportAgent", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithOne("SupportAgent")
                        .HasForeignKey("Chat_Support.Domain.Entities.SupportAgent", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportGuestChatRoomMember", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.GuestUser", "GuestUser")
                        .WithMany()
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("GuestUser");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.SupportAgent", "AssignedAgent")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedAgentUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chat_Support.Domain.Entities.ChatRoom", "ChatRoom")
                        .WithOne()
                        .HasForeignKey("Chat_Support.Domain.Entities.SupportTicket", "ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Chat_Support.Domain.Entities.GuestUser", "RequesterGuest")
                        .WithMany("SupportTickets")
                        .HasForeignKey("RequesterGuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "RequesterUser")
                        .WithMany("SupportTicketsAsRequester")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedAgent");

                    b.Navigation("ChatRoom");

                    b.Navigation("Region");

                    b.Navigation("RequesterGuest");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TicketReply", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.SupportTicket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany("TicketReplies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__TicketRep__UserI__0A9D95DB");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TodoItem", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.TodoList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TodoList", b =>
                {
                    b.OwnsOne("Chat_Support.Domain.ValueObjects.Colour", "Colour", b1 =>
                        {
                            b1.Property<int>("TodoListId")
                                .HasColumnType("int");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TodoListId");

                            b1.ToTable("TodoLists");

                            b1.WithOwner()
                                .HasForeignKey("TodoListId");
                        });

                    b.Navigation("Colour")
                        .IsRequired();
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserConnection", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", null)
                        .WithMany("Connections")
                        .HasForeignKey("KciUserId");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserFacility", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("Regionid");

                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany("UserFacilities")
                        .HasForeignKey("UserId");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.UserFcmTokenInfoMobileAbrikChat", b =>
                {
                    b.HasOne("Chat_Support.Domain.Entities.KciUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatMessage", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.ChatRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.GuestUser", b =>
                {
                    b.Navigation("ChatRooms");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciGroup", b =>
                {
                    b.Navigation("GroupFacilities");

                    b.Navigation("KciAssignedUsers");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.KciUser", b =>
                {
                    b.Navigation("ChatRoomMemberships");

                    b.Navigation("Connections");

                    b.Navigation("CreatedChatRooms");

                    b.Navigation("KciAssignedUsers");

                    b.Navigation("MessageReactions");

                    b.Navigation("MessageStatuses");

                    b.Navigation("SentMessages");

                    b.Navigation("SupportAgent");

                    b.Navigation("SupportTicketsAsRequester");

                    b.Navigation("TicketReplies");

                    b.Navigation("UploadedFiles");

                    b.Navigation("UserFacilities");

                    b.Navigation("UserRegions");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.Region", b =>
                {
                    b.Navigation("ChatRooms");

                    b.Navigation("UserRegions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.SupportAgent", b =>
                {
                    b.Navigation("AssignedTickets");
                });

            modelBuilder.Entity("Chat_Support.Domain.Entities.TodoList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
